# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neglikgrad <- function(Omega, D, G, E, pi1) {
    .Call('_caseControlGE_neglikgrad', PACKAGE = 'caseControlGE', Omega, D, G, E, pi1)
}

neghess <- function(Omega, D, G, E, pi1) {
    .Call('_caseControlGE_neghess', PACKAGE = 'caseControlGE', Omega, D, G, E, pi1)
}

hesszeta <- function(Omega, D, G, E, pi1) {
    .Call('_caseControlGE_hesszeta', PACKAGE = 'caseControlGE', Omega, D, G, E, pi1)
}

